---
apiVersion: v1
kind: Service
metadata:
  name: liftbridge-external
spec:
  selector:
    app: liftbridge
  type: NodePort
  ports:
    - name: grpc
      protocol: TCP
      port: 9292
      nodePort: 32767
      targetPort: grpc
