before:
  hooks:
    - go mod download
    - go generate ./...

builds:
- env:
  - CGO_ENABLED=0
  ignore:
    - goos: darwin
      goarch: 386

changelog:
  skip: true

archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"
