FROM golang:1.25-alpine as build-base
WORKDIR /workspace

# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download

# Copy the go source
COPY main.go main.go
COPY server/ server/

# Build
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -mod=readonly -o liftbridge

FROM debian:bookworm-slim
COPY --from=build-base /workspace/liftbridge /liftbridge
RUN apt-get update && apt-get install -y netcat-openbsd
COPY docker/dev-cluster/wait-for.sh /wait-for.sh
