host: 0.0.0.0
port: 5050
tls:
  key: ./configs/certs/server/server-key.pem
  cert: ./configs/certs/server/server-cert.pem
  client.auth.enabled: true
  client.auth.ca: ./configs/certs/ca-cert.pem
  client.authz.enabled: true
  
logging.level: error
clustering:
  server.id: a
  namespace: a
  raft.bootstrap.seed: true
nats.embedded: true
