apiVersion: v1
data:
  liftbridge.conf: |
    listen: 0.0.0.0:9292
    # data.dir: /tmp/liftbridge/server-2
    # log.level: debug

    clustering {
      min.insync.replicas: 1
    }
kind: ConfigMap
metadata:
  labels:
    app: liftbridge
    component: config
    environment: dev
    k8s-app: liftbridge
  name: config
